info:
  author: ''
  scheme: ''
  background: 'dark'
  description: ''
  license: 'MIT'
  version: '0.0.1'
colors:
  dark: '#282828'
schemas:
  darkish: '#ddd dark b'
hilinks:
  ### Vim editor colors
  ColorColumn: ''
  Conceal: ''
  Cursor: ''
  CursorIM: ''
  CursorColumn: ''
  CursorLine: ''
  Directory: ''
  DiffAdd: ''
  DiffChange: ''
  DiffDelete: ''
  DiffText: ''
  ErrorMsg: ''
  VertSplit: ''
  Folded: ''
  FoldColumn: ''
  SignColumn: ''
  IncSearch: ''
  LineNr: ''
  MatchParen: ''
  ModeMsg: ''
  MoreMsg: ''
  NonText: ''
  Normal: ''
  PMenu: ''
  PMenuSel: ''
  PmenuSbar: ''
  PmenuThumb: ''
  Question: ''
  Search: ''
  SpecialKey: ''
  SpellBad: ''
  SpellLocal: ''
  SpellCap: ''
  SpellRare: ''
  StatusLine: ''
  StatusLineNC: ''
  TabLine: ''
  TabLineFill: ''
  TabLineSel: ''
  Title: ''
  Visual: ''
  VisualNOS: ''
  WarningMsg: ''
  WildMenu: ''
  ### Standard syntax highlighting
  # Comment
  Comment: ''
  # Constant
  Constant: ''
  String: ''
  Character: ''
  Boolean: ''
  Number: ''
  Float: ''
  # Identifier
  Identifier: ''
  Function: ''
  # Statement
  Statement: ''
  Conditional: ''
  Repeat: ''
  Label: ''
  Operator: ''
  Keyword: ''
  Exception: ''
  # PreProc
  PreProc: ''
  Include: ''
  Define: ''
  Macro: ''
  PreCondit: ''
  # Type
  Type: ''
  StorageClass: ''
  Structure: ''
  Typedef: ''
  # Special
  Special: ''
  SpecialChar: ''
  Tag: ''
  Delimiter: ''
  SpecialComment: ''
  Debug: ''
  #Underlined
  Underlined: ''
  #Ignore
  Ignore: ''
  # Error
  Error: ''
  # Todo
  Todo: ''
  #### languages
  # C highlighting
  cOperator: ''
  cPreCondit: ''
  # CSS highlighting
  cssBraces: ''
  cssClassName: ''
  cssColor: ''
  # Diff highlighting
  # DiffAdded: '@DiffAdd'
  DiffFile: ''
  DiffNewFile: ''
  DiffLine: ''
  # DiffRemoved: '@DiffDelete'
  # Git highlighting
  gitCommitOverflow: ''
  gitCommitSummary: ''
  # HTML highlighting
  htmlBold: ''
  htmlItalic: ''
  htmlEndTag: ''
  htmlTag: ''
  # JavaScript highlighting
  javaScript: ''
  javaScriptBraces: ''
  javaScriptNumber: ''
  # Markdown highlighting
  markdownCode: ''
  markdownError: ''
  markdownCodeBlock: ''
  markdownHeadingDelimiter: ''
  # PHP highlighting
  phpMemberSelector: ''
  phpComparison: ''
  phpParent: ''
  # Python highlighting
  pythonOperator: ''
  pythonRepeat: ''
  # Ruby highlighting
  rubyAttribute: ''
  rubyConstant: ''
  rubyInterpolation: ''
  rubyInterpolationDelimiter: ''
  rubyRegexp: ''
  rubySymbol: ''
  rubyStringDelimiter: ''
  # SASS highlighting
  sassidChar: ''
  sassClassChar: ''
  sassInclude: ''
  sassMixing: ''
  sassMixinName: ''
  # Signify highlighting
  SignifySignAdd: ''
  SignifySignChange: ''
  SignifySignDelete: ''
  # Plugins
  # GitGutter airblade/vim-gitgutter
  GitGutterAdd: ''
  GitGutterChange: ''
  GitGutterDelete: ''
  GitGutterChangeDelete: ''
  # NERDTree scrooloose/nerdtree
  NERDTreeDirSlash: ''
  NERDTreeExecFile: ''
  # ntpeters/vim-better-whitespace
  ExtraWhitespace: ''
  # CursorLineNr
