hilinks:
  # Vim editor colors
  Bold: ''
  Debug: ''
  Directory: ''
  ErrorMsg: ''
  Exception: ''
  FoldColumn: ''
  Folded: ''
  IncSearch: ''
  Italic: ''
  Macro: ''
  MatchParen: ''
  ModeMsg: ''
  MoreMsg: ''
  Question: ''
  Search: ''
  SpecialKey: ''
  TooLong: ''
  Underlined: ''
  Visual: ''
  VisualNOS: ''
  WarningMsg: ''
  WildMenu: ''
  Title: ''
  Conceal: ''
  Cursor: ''
  NonText: ''
  Normal: ''
  LineNr: ''
  SignColumn: ''
  SpecialKey: ''
  StatusLine: ''
  StatusLineNC: ''
  VertSplit: ''
  ColorColumn: ''
  CursorColumn: ''
  CursorLine: ''
  CursorLineNr: ''
  PMenu: ''
  PMenuSel: ''
  TabLine: ''
  TabLineFill: ''
  TabLineSel: ''
  # Standard syntax highlighting
  Boolean: ''
  Character: ''
  Comment: ''
  Conditional: ''
  Constant: ''
  Define: ''
  Delimiter: ''
  Float: ''
  Function: ''
  Identifier: ''
  Include: ''
  Keyword: ''
  Label: ''
  Number: ''
  Operator: ''
  PreProc: ''
  Repeat: ''
  Special: ''
  SpecialChar: ''
  Statement: ''
  StorageClass: ''
  String: ''
  Structure: ''
  Tag: ''
  Todo: ''
  Type: ''
  Typedef: ''
  # C highlighting
  cOperator: ''
  cPreCondit: ''
  # CSS highlighting
  cssBraces: ''
  cssClassName: ''
  cssColor: ''
  # Diff highlighting
  DiffAdd: ''
  DiffChange: ''
  DiffDelete: ''
  DiffText: ''
  DiffAdded: ''
  DiffFile: ''
  DiffNewFile: ''
  DiffLine: ''
  DiffRemoved: ''
  # Git highlighting
  gitCommitOverflow: ''
  gitCommitSummary: ''
  # GitGutter highlighting
  GitGutterAdd: ''
  GitGutterChange: ''
  GitGutterDelete: ''
  GitGutterChangeDelete: ''
  # HTML highlighting
  htmlBold: ''
  htmlItalic: ''
  htmlEndTag: ''
  htmlTag: ''
  # JavaScript highlighting
  javaScript: ''
  javaScriptBraces: ''
  javaScriptNumber: ''
  # Markdown highlighting
  markdownCode: ''
  markdownError: ''
  markdownCodeBlock: ''
  markdownHeadingDelimiter: ''
  # NERDTree highlighting
  NERDTreeDirSlash: ''
  NERDTreeExecFile: ''
  # PHP highlighting
  phpMemberSelector: ''
  phpComparison: ''
  phpParent: ''
  # Python highlighting
  pythonOperator: ''
  pythonRepeat: ''
  # Ruby highlighting
  rubyAttribute: ''
  rubyConstant: ''
  rubyInterpolation: ''
  rubyInterpolationDelimiter: ''
  rubyRegexp: ''
  rubySymbol: ''
  rubyStringDelimiter: ''
  # SASS highlighting
  sassidChar: ''
  sassClassChar: ''
  sassInclude: ''
  sassMixing: ''
  sassMixinName: ''
  # Signify highlighting
  SignifySignAdd: ''
  SignifySignChange: ''
  SignifySignDelete: ''
  # Spelling highlighting
  SpellBad: ''
  SpellLocal: ''
  SpellCap: ''
  SpellRare: ''
