info:
  author: ''
  scheme: ''
  background: 'dark'
  description: ''
  license: 'MIT'
  version: '0.0.1'
colors:
  dark: '#282828'
hilinks:
  ### Vim editor colors
  ColorColumn: ''
  Conceal: ''
  Cursor: ''
  CursorIM: ''
  CursorColumn: ''
  CursorLine: ''
  Directory: ''
  DiffAdd: ''
  DiffChange: ''
  DiffDelete: ''
  DiffText: ''
  ErrorMsg: ''
  VertSplit: ''
  Folded: ''
  FoldColumn: ''
  SignColumn: ''
  IncSearch: ''
  LineNr: ''
  MatchParen: ''
  ModeMsg: ''
  MoreMsg: ''
  NonText: ''
  Normal: ''
  PMenu: ''
  PMenuSel: ''
  PmenuSbar: ''
  PmenuThumb: ''
  Question: ''
  Search: ''
  SpecialKey: ''
  SpellBad: ''
  SpellLocal: ''
  SpellCap: ''
  SpellRare: ''
  StatusLine: ''
  StatusLineNC: ''
  TabLine: ''
  TabLineFill: ''
  TabLineSel: ''
  Title: ''
  Visual: ''
  VisualNOS: ''
  WarningMsg: ''
  WildMenu: ''
  ### Standard syntax highlighting
  # Comment
  Comment: ''
  # Constant
  Constant: ''
  String: '' # Constant
  Character: '' # Constant
  Boolean: '' # Constant
  Number: '' # Constant
  Float: '' # Constant
  # Identifier
  Identifier: ''
  Function: '' # Identifier
  # Statement
  Statement: ''
  Conditional: '' # Statement
  Repeat: '' # Statement
  Label: '' # Statement
  Operator: '' # Statement
  Keyword: '' # Statement
  Exception: '' # Statement
  # PreProc
  PreProc: ''
  Include: '' # PreProc
  Define: '' # PreProc
  Macro: '' # PreProc
  PreCondit: '' # PreProc
  # Type
  Type: ''
  StorageClass: '' # Type
  Structure: '' # Type
  Typedef: '' # Type
  # Special
  Special: ''
  SpecialChar: '' # Special
  Tag: '' # Special
  Delimiter: '' # Special
  SpecialComment: '' # Special
  Debug: '' # Special
  #Underlined
  Underlined: ''
  #Ignore
  Ignore: ''
  # Error
  Error: ''
  # Todo
  Todo: ''
  # help
  helpNote: ''
  helpHeadline: ''
  helpStar: '' # Ignore
  helpHyperTextEntry: '' # helpStar
  helpHyperTextJump: '' # Identifier
  helpSectionDelim: '' # PreProc
  #### languages
  # json
  json: ''
  jsonQuote: '' # Quote
  jsonString: '' # String
  jsonKeywordMatch: '' # no link
  jsonKeyword: '' # Label > Statement
  jsonBraces: '' # Delimiter > Special
  jsonNumber: '' # Delimiter > Special
  jsonBoolean: '' # Delimiter > Special
  # vimScript
  vimError: ''
  vimCommentTitle: ''  # PreProc
  vimComment: ''  # Comment
  vimString: ''  # String
  vimNumber: ''  # Number
  vimOper: ''  # Operator
  vimVar: ''  # Identifier
  vimCommand: ''  # Statement
  vimNorm: ''  # vimCommand
  vimNormCmds: ''  # no link
  vimIsCommand: ''  # no link
  vimParenSep: ''  # Delimiter > Special
  # C highlighting
  cOperator: ''
  cPreCondit: ''
  # CSS highlighting
  cssBraces: ''
  cssClassName: ''
  cssColor: ''
  # Diff highlighting
  DiffAdded: '' # DiffAdd
  DiffFile: ''
  DiffNewFile: ''
  DiffLine: ''
  DiffRemoved: '' # DiffDelete
  # Git highlighting
  gitCommitOverflow: ''
  gitCommitSummary: ''
  # HTML highlighting
  htmlBold: ''
  htmlItalic: ''
  htmlEndTag: ''
  htmlTag: ''
  # JavaScript highlighting
  javaScriptBraces: '' # no link
  javaScriptBoolean: '' # Boolean
  javaScriptComment: '' # Comment
  javaScriptConditional: '' # Conditional
  javaScriptExceptions: '' # Special
  javaScriptFuncArg: '' # no link
  javaScriptFuncComma: '' # Operator
  javaScriptFuncKeyword: '' # Function
  javaScriptFuncExp: '' # Title
  javaScriptIdentifier: '' # Identifier
  javaScriptLogicSymbols: '' # Operator
  javaScriptNumber: '' # Number
  javaScriptObjectKey: '' # No link
  javaScriptOperator: '' # no link
  javaScriptOpSymbols: '' # no link
  javaScriptParens: '' # no link
  javaScriptReserved: '' # Keyword > Statement
  javaScriptStatement: '' # Statement
  javaScriptString: '' # String
  javaScriptTemplateString: '' # String
  # js Docs
  javaScriptDocTags: '' # Special
  javaScriptDocSeeTag: '' # Function
  javaScriptDocComment: '' # Comment
  # Markdown highlighting
  markdownCode: ''
  markdownError: ''
  markdownCodeBlock: ''
  markdownHeadingDelimiter: ''
  # PHP highlighting
  phpMemberSelector: ''
  phpComparison: ''
  phpParent: ''
  # Python highlighting
  pythonOperator: ''
  pythonRepeat: ''
  # Ruby highlighting
  rubyAttribute: ''
  rubyConstant: ''
  rubyInterpolation: ''
  rubyInterpolationDelimiter: ''
  rubyRegexp: ''
  rubySymbol: ''
  rubyStringDelimiter: ''
  # SASS highlighting
  sassidChar: ''
  sassClassChar: ''
  sassInclude: ''
  sassMixing: ''
  sassMixinName: ''
  # Signify highlighting
  SignifySignAdd: ''
  SignifySignChange: ''
  SignifySignDelete: ''
  # Plugins
  # GitGutter airblade/vim-gitgutter
  GitGutterAdd: ''
  GitGutterChange: ''
  GitGutterDelete: ''
  GitGutterChangeDelete: ''
  # NERDTree scrooloose/nerdtree
  NERDTreeClosable: ''
  NERDTreeDir: '' # link directory
  NERDTreeDirSlash: ''
  NERDTreeExecFile: ''
  NERDTreeHelp: '' # no link
  NERDTreeHelpCommand: '' # no link
  NERDTreeHelpKey: '' # Identifier
  NERDTreeHelpTitle: '' # Macro > PreProc
  NERDTreeIgnore: '' # Ignore
  NERDTreeOpenable: ''
  NERDTreeToggleOn: '' # Question
  NERDTreeToggleOff: '' # WarningMsg
  # ntpeters/vim-better-whitespace
  ExtraWhitespace: ''
  # CursorLineNr
  yamlBlockMappingKey: '' # Identifier
  yamlFlowCollection: '' # no link
  yamlFlowIndicator: '' # Special
  yamlFlowString: '' # no link
  yamlFlowStringDelimiter: '' # no link
  yamlInteger: '' # Number
  yamlKeyFlowMapping: '' # yamlFlowIndicator > Special
  yamlKeyValueDelimiter: '' # no link
  # vim-plug
  plugName: '' # Label > Statement
  plugDash: '' # Special
  plugStar: '' # Boolean
  plugNumber: '' # Number
  plug1: '' # Title
  plug2: '' # Repeat > Statement
  plugBracket: '' # Structure > Type
